### PR TITLE
fix: Ensure bundle can be installed from alpha channel on openshift 4.15

### LINKED ISSUE #344: kepler operator missing in OCP 4.15
OpenShift version: 4.15.0-rc.2

In OpenShift, go to Operators > OperatorHub.  Search for "kepler".  Nothing shows up.  It is there in 4.14.

### PR DESCRIPTION
**Pull request by sthaha**
Fixed #344

### CODE REVIEW

**Review by vprashar2929 — APPROVED** [review]
LGTM

File: hack/bundle.sh [hunk 1]
```diff
@@ -95,7 +95,7 @@ main() {
 	info "Adding additional metadata annotations"
 	cat <<-EOF >>bundle/metadata/annotations.yaml
 		# Annotations for OpenShift version
-		  com.redhat.openshift.versions: "v4.11-v4.14"
+		  com.redhat.openshift.versions: "v4.12-v4.17"
```
Comment (vimalk78) [inline hack/bundle.sh:98]: didn't we decide on 4.14-4.17?

Comment (sthaha) [reply hack/bundle.sh:98]: for the downstream .. yes. does not apply to the upstream one.
